# Generated by Django 2.1.1 on 2018-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20181227_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='freeDay',
            new_name='freeTime',
        ),
        migrations.AlterField(
            model_name='event',
            name='timeChosen',
            field=models.CharField(max_length=256),
        ),
    ]
